In [1]:
import sys
sys.path.insert(0,'/home/ernie/caffe2/build')
from caffe2.python import cnn, workspace, core
from caffe2.proto import caffe2_pb2
import numpy as np
import time

In [2]:
X = np.arange(12).reshape(2,2,3)
print X

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [4]:
net = core.Net("mynet")
net.Transpose(["X"],["Y"],axes=[2,0,1])
workspace.FeedBlob("X",X)
workspace.CreateNet(net.Proto())
net.TransposeGradient(["Y"],"X",axes=[1,2,0])
workspace.RunNet("mynet",1)
Y = workspace.FetchBlob("Y")

print Y.shape
print Y

AttributeError: Method TransposeGradient is not a registered operator. Did you mean: []