In [1]:
%matplotlib inline
import sys
sys.path.insert(0,'/home/ernie/caffe2/build')
from matplotlib import pyplot
import numpy as np
import os
import shutil
from IPython import display

from caffe2.python import core, model_helper, net_drawer, workspace, visualize, brew

# If you would like to see some really detailed initializations,
# you can change --caffe2_log_level=0 to --caffe2_log_level=-1
core.GlobalInit(['caffe2', '--caffe2_log_level=0'])

In [2]:
op = core.CreateOperator(
    "AnnotationInput",
    [],
    ["Y","Z"],
    db = "/home/ernie/data/VOCdevkit/VOC0712/lmdb/VOC0712_trainval_lmdb",
    batch_size=1 ,
    scale = 300,
    crop = 300,
    use_gpu_transform = 0,
   # minsize = 332,
    mirror = 0,
    warp = 1,
    color = 1,
    use_caffe_datum = 1,
    db_type = "lmdb",
    interp_mode = ["LINEAR","AREA","NEAREST","CUBIC","LANCZOS4"],
    decode_threads = 1
)

In [3]:
print ("Type of the created op is {}".format(type(op)))
print ("Content:\n")
print (str(op))

Type of the created op is <class 'caffe2.proto.caffe2_pb2.OperatorDef'>
Content:

output: "Y"
output: "Z"
name: ""
type: "AnnotationInput"
arg {
  name: "scale"
  i: 300
}
arg {
  name: "use_caffe_datum"
  i: 1
}
arg {
  name: "color"
  i: 1
}
arg {
  name: "use_gpu_transform"
  i: 0
}
arg {
  name: "db"
  s: "/home/ernie/data/VOCdevkit/VOC0712/lmdb/VOC0712_trainval_lmdb"
}
arg {
  name: "crop"
  i: 300
}
arg {
  name: "interp_mode"
  strings: "LINEAR"
  strings: "AREA"
  strings: "NEAREST"
  strings: "CUBIC"
  strings: "LANCZOS4"
}
arg {
  name: "warp"
  i: 1
}
arg {
  name: "batch_size"
  i: 1
}
arg {
  name: "mirror"
  i: 0
}
arg {
  name: "decode_threads"
  i: 1
}
arg {
  name: "db_type"
  s: "lmdb"
}



In [4]:
workspace.RunOperatorOnce(op)

True

In [5]:
np.set_printoptions(threshold=np.NaN)
#print("Y:\n{}".format(workspace.FetchBlob("Y")))
Y = workspace.FetchBlob("Y")
print Y.shape
Z = workspace.FetchBlob("Z")
print Z

(1, 300, 300, 3)
[[[[  0.          15.           0.           0.27448609   0.44808736
      0.50423217   1.           0.        ]
   [  0.          15.           1.           0.03143894   0.41712198
      0.2853688    1.           0.        ]]]]


In [6]:
print Y

[[[[  1   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   0]
   [  0   0   

In [7]:
from PIL import Image
data = np.reshape(Y,(300,300,3))
print data.dtype
data = data.astype('uint8')
print np.shape(data)

new_im = Image.fromarray(data)
new_im.show()

uint8
(300, 300, 3)


In [10]:
workspace.RunOperator(op)

AttributeError: 'module' object has no attribute 'RunOperator'

In [9]:
Y = workspace.FetchBlob("Y")
print Y.shape
Z = workspace.FetchBlob("Z")
print Z

(3, 300, 300, 3)
[[[[  0.          12.           0.           0.13597734   0.47999999
      0.55240792   0.74199998   0.        ]
   [  0.          15.           0.           0.02266289   0.024
      0.99716711   0.99599999   0.        ]
   [  1.          19.           0.           0.41492537   0.40000001
      0.61791044   0.602        0.        ]
   [  2.          18.           0.           0.24600001   0.41333333
      0.43000001   0.51999998   0.        ]
   [  2.           9.           0.           0.47799999   0.41600001
      0.61400002   0.54666668   0.        ]]]]


In [11]:
net = core.Net("test net")
print ("Current network proto:\n\n{}".format(net.Proto()))

Current network proto:

name: "test net"



In [18]:
op = net.AnnotationInput(
    [],
    ["Y","Z"],
    db = "/home/ernie/data/VOCdevkit/VOC0712/lmdb/VOC0712_test_lmdb",
    batch_size=3 ,
    scale = 300,
    crop = 300,
    use_gpu_transform = 1,
   # minsize = 332,
    warp = 1,
    color = 1,
    use_caffe_datum = 1,
    db_type = "lmdb",
    interp_mode = ['LINEAR','AREA','NEAREST','CUBIC','LANCZOS4']
)
#net.Proto().op.append(op)

In [19]:
print("Current network proto:\n\n{}".format(net.Proto()))

Current network proto:

name: "test net"
op {
  output: "Y"
  output: "Z"
  name: ""
  type: "AnnotationInput"
  arg {
    name: "scale"
    i: 300
  }
  arg {
    name: "crop"
    i: 300
  }
  arg {
    name: "use_caffe_datum"
    i: 1
  }
  arg {
    name: "color"
    i: 1
  }
  arg {
    name: "db_type"
    s: "lmdb"
  }
  arg {
    name: "db"
    s: "/home/ernie/data/VOCdevkit/VOC0712/lmdb/VOC0712_test_lmdb"
  }
  arg {
    name: "warp"
    i: 1
  }
  arg {
    name: "interp_mode"
    strings: "LINEAR"
    strings: "AREA"
    strings: "NEAREST"
    strings: "CUBIC"
    strings: "LANCZOS4"
  }
  arg {
    name: "batch_size"
    i: 3
  }
  arg {
    name: "use_gpu_transform"
    i: 1
  }
}



In [20]:
print("Current blobs in the workspace: {}".format(workspace.Blobs()))

Current blobs in the workspace: [u'Y', u'Z']


In [21]:
workspace.RunNetOnce(net)

True

In [23]:
Z = workspace.FetchBlob("Z")
print Z

[[[[  0.          12.           0.           0.13597734   0.47999999
      0.55240792   0.74199998   0.        ]
   [  0.          15.           0.           0.02266289   0.024
      0.99716711   0.99599999   0.        ]
   [  1.          19.           0.           0.41492537   0.40000001
      0.61791044   0.602        0.        ]
   [  2.          18.           0.           0.24600001   0.41333333
      0.43000001   0.51999998   0.        ]
   [  2.           9.           0.           0.47799999   0.41600001
      0.61400002   0.54666668   0.        ]]]]


In [24]:
workspace.RunNetOnce(net)

True

In [25]:
Z = workspace.FetchBlob("Z")
print Z

[[[[  0.          12.           0.           0.13597734   0.47999999
      0.55240792   0.74199998   0.        ]
   [  0.          15.           0.           0.02266289   0.024
      0.99716711   0.99599999   0.        ]
   [  1.          19.           0.           0.41492537   0.40000001
      0.61791044   0.602        0.        ]
   [  2.          18.           0.           0.24600001   0.41333333
      0.43000001   0.51999998   0.        ]
   [  2.           9.           0.           0.47799999   0.41600001
      0.61400002   0.54666668   0.        ]]]]


In [27]:
workspace.CreateNet(net)
workspace.RunNet(net)
Z = workspace.FetchBlob("Z")
print Z

[[[[  0.          12.           0.           0.13597734   0.47999999
      0.55240792   0.74199998   0.        ]
   [  0.          15.           0.           0.02266289   0.024
      0.99716711   0.99599999   0.        ]
   [  1.          19.           0.           0.41492537   0.40000001
      0.61791044   0.602        0.        ]
   [  2.          18.           0.           0.24600001   0.41333333
      0.43000001   0.51999998   0.        ]
   [  2.           9.           0.           0.47799999   0.41600001
      0.61400002   0.54666668   0.        ]]]]


In [28]:
workspace.RunNet(net)
Z = workspace.FetchBlob("Z")
print Z

[[[[  0.           7.           0.           0.026        0.76600987
      0.168        0.89162564   0.        ]
   [  0.           7.           1.           0.72399998   0.81280786   1.
      0.95812809   0.        ]
   [  0.           7.           2.           0.47         0.80788177
      0.66799998   0.92364532   0.        ]
   [  0.           7.           3.           0.34999999   0.80541873
      0.50400001   0.89655173   0.        ]
   [  0.           7.           4.           0.278        0.78817731
      0.37799999   0.88423645   0.        ]
   [  0.           7.           5.           0.21600001   0.80049258
      0.30000001   0.86945814   0.        ]
   [  0.           7.           6.           0.168        0.7955665    0.242
      0.86206895   0.        ]
   [  1.          16.           0.           0.37400001   0.36000001
      0.56400001   0.64533335   0.        ]
   [  1.          11.           0.           0.308        0.55733335
      0.73799998   1.           0.      

In [29]:
print Z.shape

(1, 1, 16, 8)


In [30]:
Y = workspace.FetchBlob("Y")
print Y.shape

(3, 300, 300, 3)
